### ISSUE TITLE
Outputting Stats Above Matrix Field

### ISSUE THREAD

**Issue by jayhlee** [carlcs/craft-textstatistics#1]
I'm trying to display {{ statistics.readingTimeString }} above text blocks within a matrix field. However, because statistics is only set after it's calculated within the matrix field, I can't pull the readingTimeString above the matrix field because the statistics variable isn't set at that point.

Is there a way to have the statistics variable to be set and substantiated before the matrix field?

Also, is there a way to preparse the {{ statistics.readingTimeString }} data within a new field I create (e.g. "entry.readingTime") that would calculate the reading time when the entry is published so that I can pull the reading time data and display it on an index page of entries? For example, in addition to having the reading time on a blog entry page, I'd like to show the reading time next to a blog listing/index page. Thanks!

**Comment by carlcs** [comment]
You’re on the right path there. To output the Text Statistics data before outputting the actual content you’d have to do a separate loop through your Matrix blocks. It would be a very simple one, doing nothing more than calling `addToTextStatistics()` and `addToReadingTime()` for the various block types.

As this adds some overhead and you don’t have access to the data from index pages, your idea with using the Preparse plugin is good (if your ECM uses the same params, Craft won’t query the database twice though). You could either make the Preparse field output just the reading time, or –and this is what I did– output the complete object as a JSON string `{{ getTextStatistics()|json_encode }}` (there’s currently no `json_decode` filter in Craft but I have one in my [Helpers](https://github.com/carlcs/craft-helpers) plugin).

**Comment by jayhlee** [comment]
Thanks for the response and presenting some alternative solutions. Makes sense!
